### ISSUE TITLE
Component: Implement reusable Title component

### ISSUE THREAD

**Issue by modularcoder** [JSConfArmenia/conf-19-react#10]
Implement reusable Title component for sections titles

![image](https://user-images.githubusercontent.com/3959008/51807419-f1992200-229f-11e9-923a-124a4f2b4084.png)
![image](https://user-images.githubusercontent.com/3959008/51807420-f958c680-229f-11e9-909e-f2f76b8f3f83.png)
![image](https://user-images.githubusercontent.com/3959008/51807422-ffe73e00-229f-11e9-8028-451d6fb415f8.png)
![image](https://user-images.githubusercontent.com/3959008/51807426-05448880-22a0-11e9-9bc9-61912210a6bb.png)
![image](https://user-images.githubusercontent.com/3959008/51807428-0970a600-22a0-11e9-938e-b7460a564363.png)
![image](https://user-images.githubusercontent.com/3959008/51807431-0d9cc380-22a0-11e9-9695-0c3685a2be72.png)

**Comment by robgev** [comment]
This one's on me but I need more clearance on how exactly you want to do this.
