### ISSUE TITLE
Feature: Implement the About section

### ISSUE THREAD

**Issue by modularcoder** [JSConfArmenia/conf-19-react#11]
Implement the About section

![image](https://user-images.githubusercontent.com/3959008/51807445-3d4bcb80-22a0-11e9-9f8e-0d39c6abca04.png)

**Comment by chris-manouckson** [comment]
Hey there, glad to get in touch with you! This is my first contribution at GitHub, so I will pick this part of the project for start.

**Comment by chris-manouckson** [comment]
Thanks @nairihar. I've already cloned the repo, now familiarizing with the content. I will let you know if I have any questions in the future.

**Comment by nairihar** [comment]
@chris-manouckson, I think you should wait for these components. Or just skip that part yet.
https://github.com/JSConfArmenia/conf-19-react/issues/10

**Comment by chris-manouckson** [comment]
As I see, the `Title` and `TitleAccent`components are ready, so I can start working on the `About` section. I'd like to know from where can I get the **image on the right** and the **background image**?

**Comment by nairihar** [comment]
@chris-manouckson you can find PSD [here](https://drive.google.com/open?id=1uXK6XkCQsQssBhjYt53fJKleT0yIgrdT)

**Comment by nairihar** [comment]
@chris-manouckson seems there are are some problems, we can skip it now, but we should note to fix.

We should change the section size.
Change the max/min @media values, make row a little earlier(when decreasing window size).
Move the title and text to centre (vertical).

<img width="1401" alt="screen shot 2019-02-02 at 8 07 04 pm" src="https://user-images.githubusercontent.com/15065065/52166407-42889a80-2726-11e9-8056-bd56cebe2bd0.png">
<img width="606" alt="screen shot 2019-02-02 at 8 07 31 pm" src="https://user-images.githubusercontent.com/15065065/52166408-43213100-2726-11e9-91d2-bc0fa4260e4d.png">
