### ISSUE TITLE
Feature: Implement the Team section

### ISSUE THREAD

**Issue by modularcoder** [JSConfArmenia/conf-19-react#14]
Implement the Team section

![image](https://user-images.githubusercontent.com/3959008/51807477-ac292480-22a0-11e9-916a-d84c9cc7646b.png)

**Comment by lghandilyan-vineti** [comment]
I can work on this
To make everything clear
Needs:
I need the background image,
The team's images
Questions:
The website is going to be responsive, right?
(If yes I will be using bootstrap)
As the title is a reusable component, shall I just leave a plain text for now?

**Comment by nairihar** [comment]
Hi @ghlilit, all the icons, image, colours you can find in PSD file(see in README).
Yes, the website should be responsive. I think bootstrap is ok for that.
The title we can add later when the reusable component will be ready.

**Comment by modularcoder** [comment]
@ghlilit great, thanks.

The website PSD is here. I guess we'll need to leave the section background trabsparent, because there's a single big gradient through all the sections.
https://github.com/JSConfArmenia/conf-19-react#materials

The team's images could be found here
https://github.com/JSConfArmenia/conf-18/tree/master/public/team

- Yes the website should be responsive
- We may use bootstrap, or maybe [boolma](https://bulma.io/) as well
https://alligator.io/react/intro-react-bulma-components/

I guess then this issue should be closed first
https://github.com/JSConfArmenia/conf-19-react/issues/24

Do you want to tak that as well? :)

**Comment by modularcoder** [comment]
@ghlilit invited you to the repo as collaborator

**Comment by ghlilit** [comment]
I can only start in a couple days and I would not want to block others. If by the time I have free time nobody takes care of the main layout, I will think about it. 
Thanks for the answers.

**Comment by VamOSGS** [comment]
@ghlilit will you work on this? or I can start?
