### ISSUE TITLE
Feature: Implement the FAQ section

### ISSUE THREAD

**Issue by modularcoder** [JSConfArmenia/conf-19-react#17]
Implement the FAQ section

![image](https://user-images.githubusercontent.com/3959008/51807494-df6bb380-22a0-11e9-8051-0b56dc1abca9.png)

**Comment by bagshik** [comment]
Hey, I can take care of this one. What are our plans for the layout / grid system? Bootstrap 4?

**Comment by nairihar** [comment]
@bagshik I think this will be useful.
https://github.com/JSConfArmenia/conf-18/blob/master/src/Faq/Faq.vue

**Comment by nairihar** [comment]
@modularcoder what about grid system? Bootstrap?

**Comment by modularcoder** [comment]
I think loading the whole bootstrap lib just for the grid really sucks.

Option 1 load only grid part from bootstrap
Option 2 load only grid part from bulma react
Option 3 use some css grid npm package

**Comment by bagshik** [comment]
@nairihar thanks, that's exactly what I needed 👌 
@modularcoder everyone's familiar with bootstrap, so I guess option 1 is the way to go 🤔

**Comment by modularcoder** [comment]
@nairihar, can we follow up with @robgev, to see if he has set up any grid?

If no, let's open a separate issue for setting up the grid and deploy it with separate PR

**Comment by nairihar** [comment]
https://github.com/JSConfArmenia/conf-19-react/issues/24#event-2102730024

**Comment by bagshik** [comment]
Hi guys, as I was building this section I noticed that we're still missing bootstrap's styles in order for react-bootstrap to work (the grid system doesn't work without it). We should at least import the grid system, what do you think?

**Comment by nairihar** [comment]
Hi @bagshik, we have just integrated bootstrap grid.
So you can use the bootstrap grid for this section.
