### ISSUE TITLE
Feature: Implement the Jobs section

### ISSUE THREAD

**Issue by modularcoder** [JSConfArmenia/conf-19-react#19]
Implement the Jobs section

![image](https://user-images.githubusercontent.com/3959008/51807505-0aee9e00-22a1-11e9-9210-668b55b738c4.png)

**Comment by Vahe83** [comment]
Hi.
Are there any deadline for implementation?

**Comment by modularcoder** [comment]
@Vahe83 this one isn't very urgent, we don't have any job contents yet :)
Do you want to work on this?

**Comment by Vahe83** [comment]
Yes, I do.

**Comment by modularcoder** [comment]
@Vahe83 invited you to the repo. You may start working once the main layout would be set up.

https://github.com/JSConfArmenia/conf-19-react/issues/24

**Comment by bagshik** [comment]
Has there been progress on this issue?

**Comment by Vahe83** [comment]
I don't have any jobs content to start implement that. Maybe I create components with dummy data?

**Comment by bagshik** [comment]
Ah my bad, I thought the data was already available. I don't know, maybe @modularcoder can shed some light on this.

**Comment by Vahe83** [comment]
@modularcoder are there any data for the task?

**Comment by modularcoder** [comment]
@bagshik @Vahe83 Hi.
There's no data for this section at the moment

Maybe we can implement this component with some Fake data and leave it as commented out for now?

**Comment by Vahe83** [comment]
Sure, I can implement the task with fake data till we will have available jobs.

**Comment by nairihar** [comment]
@Vahe83 we have invited you to the repo as a collaborator. Please accept the invitation, so I will assign this task to you.

**Comment by Vahe83** [comment]
@nairihar already confirmed.

**Comment by Vahe83** [comment]
@modularcoder @nairihar I have already pushed on dev-jobs branch.

**Comment by nairihar** [comment]
@Vahe83 Can you open a PR?
