### ISSUE TITLE
Feature: Setup webfonts

### ISSUE THREAD

**Issue by modularcoder** [JSConfArmenia/conf-19-react#22]
Convert otf fonts to webfonts and setup in the project
https://drive.google.com/open?id=180u5JPJA6dU5Vo1Lglw2CTB2w0H6tz9Q

**Comment by bagshik** [comment]
Բարի երեկո! I can take this one, I'll be using [Transfonter](https://transfonter.org/) to convert the fonts.

**Comment by nairihar** [comment]
Hi @bagshik, I have just invited you to the repo as a collaborator.

**Comment by bagshik** [comment]
Sure, but shouldn't we convert from OTF to support all environments? For example :
```
@font-face {
  font-family: 'FontName';
  src: url('webfont.eot'); /* IE9+ Compat Modes */
  src: url('webfont.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('webfont.woff2') format('woff2'), /* Super modern browsers */
       url('webfont.woff') format('woff'), /* Modern browsers */
       url('webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
       url('webfont.svg#FontName') format('svg'); /* Legacy iOS */
}
```

**Comment by nairihar** [comment]
oops, I forgot about that, thanks for the notice, I will reopen and assign the issue to you.
