### ISSUE TITLE
Component: Implement reusable Button component

### ISSUE THREAD

**Issue by modularcoder** [JSConfArmenia/conf-19-react#9]
Implement button as a configurable styled component

![image](https://user-images.githubusercontent.com/3959008/51807344-1e006e80-229f-11e9-8f2e-38efeca96f2b.png)
![image](https://user-images.githubusercontent.com/3959008/51807348-23f64f80-229f-11e9-8033-e00d0e4414c8.png)

![image](https://user-images.githubusercontent.com/3959008/51807354-2eb0e480-229f-11e9-9432-2058f0440be0.png)

![image](https://user-images.githubusercontent.com/3959008/51807356-32dd0200-229f-11e9-92cf-ea5c55aadd54.png)

**Comment by robgev** [comment]
I will do this.
